export enum LocalType {
    ADDMESSAGE = 'ADDMESSAGE',
    ADDMYMESSAGE = 'ADDMYMESSAGE',
    ERROR = 'ERROR',
    ADDMYCHANNELMESSAGE = 'ADDMYCHANNELMESSAGE',
    ADDCHANNELMESSAGE = 'ADDCHANNELMESSAGE',
    FRIENDJOIN="FRIENDJOIN",
    FRIENDLEAVE="FRIENDLEAVE"
}