export enum LocalType {
    ADDMESSAGE = 'ADDMESSAGE',
    ERROR = 'ERROR', ADDMYMESSAGE = 'ADDMYMESSAGE',
    ADDMYCHANNELMESSAGE = 'ADDMYCHANNELMESSAGE',
    REFRESHCHANNELMESSAGES = 'REFRESHCHANNELMESSAGES',
    NEWACTIVEFRIEND="NEWACTIVEFRIEND"
}